name: lando-d9
recipe: drupal9
config:
  webroot: web/

services:
  appserver:
    ssl: false
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database

tooling:
  drush:
    cmd: "/app/vendor/bin/drush --root=/app/web"
  drupal:
    cmd: "/app/vendor/bin/drupal --root=/app/web"
  drupalcs:
    service: appserver
    cmd: /app/vendor/bin/phpcs --standard=Drupal --extensions=php,module,inc,install,test,profile,theme,css,info,txt,md,yml 
  drupalcbf:
    service: appserver
    cmd: /app/vendor/bin/phpcbf --standard=Drupal,DrupalPractice
  phix:
    service: appserver
    cmd: '/app/vendor/bin/phpcbf --standard=vendor/drupal/coder/coder_sniffer/Drupal,vendor/drupal/coder/coder_sniffer/DrupalPractice --extensions=php,module,inc --report=full'
  drck:
    description: Run drupal-check for Drupal 9 compatibility e.g. 'lando drck ./'
    service: appserver
    cmd: /app/vendor/bin/drupal-check
  phpstan:
    service: appserver
    cmd: /app/vendor/bin/phpstan
  rector:
    service: appserver
    cmd: /app/vendor/bin/rector process
  phpunit:
    description: Runs PHPUnit commands
    user: www-data
    cmd:
      - appserver: "php /app/vendor/bin/phpunit -c /app/phpunit.xml --testdox"
      